# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  config.vm.define "app_default", primary: true do |app|
      config.vm.hostname = "app.local"
      app.vm.network :private_network, ip: "192.168.56.11"
      app.vm.provider :virtualbox do |v|
        v.gui = false
        v.memory = 256  
        v.cpus = 1
      end
  end

  config.vm.define "app_tuned", primary: true do |app2|
      config.vm.hostname = "app2.local"
      app2.vm.network :private_network, ip: "192.168.56.7"
      app2.vm.provider :virtualbox do |v|
         v.gui = false
         v.memory = 256
         v.cpus = 1
      end
  end
 

  config.vm.provider "libvirt" do |libvirt|
      libvirt.storage_pool_name = "ext_storage"
  end

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.groups = {
          "app_server" => ["app_default", "app_tuned"],
      }
  end

  if Vagrant.has_plugin?("vagrant-hostmanager")
      config.hostmanager.enabled = true
      config.hostmanager.manage_host = true
      config.hostmanager.manage_guest = true
  end
end
